


import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asif Shahriar
 */
public class Home extends javax.swing.JFrame {

   static String dname,dcell,dbg,dcity,duser,dpass,ddate;
   static long time;
   static int total;
   
   
   
    public Home() {
        initComponents();
        setfalse();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setfalse(){
        Edit.setVisible(false);
        searchpanel.setVisible(false);
        Profile.setVisible(false);
        showallpanel.setVisible(false);
        deletepanel.setVisible(false);
        proname.setText(dname);
         totaldis.setText("");
         alltotal.setText("");
    }
    
  
            
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING); 
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
   
         }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        proname = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        search = new javax.swing.JButton();
        showall = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Profile = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        name1 = new javax.swing.JLabel();
        cell1 = new javax.swing.JLabel();
        blood1 = new javax.swing.JLabel();
        city1 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        pass1 = new javax.swing.JLabel();
        passhide = new javax.swing.JPasswordField();
        edit = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        deletepanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        Edit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        submitedit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        ecell = new javax.swing.JTextField();
        ebg = new javax.swing.JComboBox<String>();
        ecity = new javax.swing.JComboBox<String>();
        euser = new javax.swing.JTextField();
        epass = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        epass1 = new javax.swing.JPasswordField();
        eday = new javax.swing.JComboBox<String>();
        emonth = new javax.swing.JComboBox<String>();
        eyear = new javax.swing.JComboBox<String>();
        searchpanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        totaldis = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        bserach = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        bgbox = new javax.swing.JComboBox<String>();
        citybox = new javax.swing.JComboBox<String>();
        day = new javax.swing.JComboBox<String>();
        month = new javax.swing.JComboBox<String>();
        year = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        showdis = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        showallpanel = new javax.swing.JPanel();
        alltotal = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        showalldis = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(249, 89, 14));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Donor's Den");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 0, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        jPanel4.setBackground(new java.awt.Color(52, 73, 94));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        proname.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        proname.setForeground(new java.awt.Color(255, 255, 255));
        proname.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel4.add(proname, gridBagConstraints);

        profile.setBackground(new java.awt.Color(52, 73, 94));
        profile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profile.setBorder(null);
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        profile.setFocusable(false);
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel4.add(profile, gridBagConstraints);

        logout.setBackground(new java.awt.Color(52, 73, 94));
        logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.setBorder(null);
        logout.setFocusable(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 196, 0);
        jPanel4.add(logout, gridBagConstraints);

        search.setBackground(new java.awt.Color(52, 73, 94));
        search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(null);
        search.setFocusable(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 87;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanel4.add(search, gridBagConstraints);

        showall.setBackground(new java.awt.Color(52, 73, 94));
        showall.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showall.setForeground(new java.awt.Color(255, 255, 255));
        showall.setText("Show All");
        showall.setBorder(null);
        showall.setFocusable(false);
        showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        jPanel4.add(showall, gridBagConstraints);

        delete.setBackground(new java.awt.Color(52, 73, 94));
        delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete Ac");
        delete.setBorder(null);
        delete.setFocusable(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        jPanel4.add(delete, gridBagConstraints);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 390));

        jPanel5.setBackground(new java.awt.Color(52, 73, 94));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 660, 30));

        Profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel14.setText("Name:");
        Profile.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 94, 49, -1));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel15.setText("Cell No:");
        Profile.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 119, 64, -1));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel16.setText("City:");
        Profile.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 169, 37, -1));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel17.setText("Blood Group:");
        Profile.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 144, 105, -1));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel18.setText("Password:");
        Profile.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 219, -1, -1));

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel19.setText("Username:");
        Profile.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 194, 105, -1));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabel20.setText("Profile");
        Profile.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, 61, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        Profile.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 46, 61, 10));

        name1.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        name1.setText("Asif");
        Profile.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 90, 186, -1));

        cell1.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        cell1.setText("01521423596");
        Profile.add(cell1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 115, 186, -1));

        blood1.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        blood1.setText("B+");
        Profile.add(blood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 140, 105, -1));

        city1.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        city1.setText("Dhaka");
        Profile.add(city1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 165, 176, -1));

        user1.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        user1.setText("asif");
        Profile.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 190, 186, -1));

        pass1.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        pass1.setText("123");
        Profile.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 135, -1));

        passhide.setBackground(new java.awt.Color(240, 240, 240));
        passhide.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        passhide.setText("jPasswordField1");
        passhide.setBorder(null);
        Profile.add(passhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 140, -1));

        edit.setBackground(new java.awt.Color(52, 73, 94));
        edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit.setFocusable(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        Profile.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 11, 63, 29));

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel21.setText("Last Donation:");
        Profile.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 244, -1, -1));

        date1.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        date1.setText("3-10-2018");
        Profile.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 244, 157, -1));

        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Profile.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        getContentPane().add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 620, 360));

        jLabel32.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel32.setText("Password:");

        jLabel33.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel33.setText("Username:");

        jLabel34.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(52, 73, 94));
        jLabel34.setText("Delete Account");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        jButton10.setBackground(new java.awt.Color(52, 73, 94));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Delete");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        user.setEditable(false);
        user.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N

        pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout deletepanelLayout = new javax.swing.GroupLayout(deletepanel);
        deletepanel.setLayout(deletepanelLayout);
        deletepanelLayout.setHorizontalGroup(
            deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepanelLayout.createSequentialGroup()
                .addGap(0, 156, Short.MAX_VALUE)
                .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deletepanelLayout.createSequentialGroup()
                        .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(23, 23, 23)
                        .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(101, 101, 101))
        );
        deletepanelLayout.setVerticalGroup(
            deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        getContentPane().add(deletepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 620, 360));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel7.setText("Cell No:");

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel8.setText("City:");

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel9.setText("Blood Group:");

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel10.setText("Password:");

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel11.setText("User Name:");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(52, 73, 94));
        jLabel12.setText("Edit Profile");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        submitedit.setBackground(new java.awt.Color(52, 73, 94));
        submitedit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitedit.setForeground(new java.awt.Color(255, 255, 255));
        submitedit.setText("Submit");
        submitedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitedit.setFocusable(false);
        submitedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submiteditActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel13.setText("Last Donation:");

        ename.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        ename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enameMouseClicked(evt);
            }
        });

        ecell.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        ecell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ecellMouseClicked(evt);
            }
        });

        ebg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ebg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));
        ebg.setBorder(null);

        ecity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ecity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bagerhat ", "Bandarban ", "Barguna ", "Barisal ", "Bhola ", "Bogra ", "Brahmanbaria ", "Chandpur ", "Chittagong ", "Chuadanga ", "Comilla ", "Cox's Bazar ", "Dhaka ", "Dinajpur ", "Faridpur ", "Feni ", "Gaibandha ", "Gazipur ", "Gopalganj ", "Habiganj ", "Jaipurhat ", "Jamalpur ", "Jessore ", "Jhalakati ", "Jhenaidah ", "Khagrachari ", "Khulna ", "Kishoreganj ", "Kurigram ", "Kushtia ", "Lakshmipur ", "Lalmonirhat ", "Madaripur ", "Magura ", "Manikganj ", "Meherpur ", "Moulvibazar ", "Munshiganj ", "Mymensingh ", "Naogaon ", "Narail ", "Narayanganj ", "Narsingdi ", "Natore ", "Nawabganj ", "Netrakona ", "Nilphamari ", "Noakhali ", "Pabna ", "Panchagarh ", "Parbattya Chattagram", "Patuakhali ", "Pirojpur ", "Rajbari ", "Rajshahi ", "Rangpur ", "Satkhira ", "Shariatpur ", "Sherpur ", "Sirajganj ", "Sunamganj ", "Sylhet ", "Tangail ", "Thakurgaon " }));
        ecity.setBorder(null);

        euser.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        euser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                euserMouseClicked(evt);
            }
        });
        euser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euserActionPerformed(evt);
            }
        });

        epass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        epass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                epassMouseClicked(evt);
            }
        });
        epass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                epassKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel22.setText("Confirm Password:");

        epass1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        epass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                epass1MouseClicked(evt);
            }
        });

        eday.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        emonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        eyear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2019", "2018", "2017" }));

        javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
        Edit.setLayout(EditLayout);
        EditLayout.setHorizontalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitedit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EditLayout.createSequentialGroup()
                                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ename)
                                    .addComponent(ecell)
                                    .addComponent(ebg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ecity, 0, 235, Short.MAX_VALUE)
                                    .addComponent(euser)
                                    .addComponent(epass)
                                    .addComponent(epass1)
                                    .addGroup(EditLayout.createSequentialGroup()
                                        .addComponent(eday, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emonth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eyear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(EditLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        EditLayout.setVerticalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EditLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(EditLayout.createSequentialGroup()
                        .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ecell, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ecity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(euser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(epass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(epass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(eday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitedit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 620, 360));

        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel25.setText("City:");
        searchpanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 37, -1));

        jLabel26.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel26.setText("Blood Group:");
        searchpanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 105, -1));

        totaldis.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        totaldis.setForeground(new java.awt.Color(52, 73, 94));
        totaldis.setText("Search");
        searchpanel.add(totaldis, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        searchpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 36, 52, 10));

        bserach.setBackground(new java.awt.Color(52, 73, 94));
        bserach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bserach.setForeground(new java.awt.Color(255, 255, 255));
        bserach.setText("Search");
        bserach.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bserach.setFocusable(false);
        bserach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bserachActionPerformed(evt);
            }
        });
        searchpanel.add(bserach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 64, 29));

        jLabel30.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel30.setText("Required Date:");
        searchpanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        bgbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bgbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));
        bgbox.setBorder(null);
        searchpanel.add(bgbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        citybox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        citybox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bagerhat ", "Bandarban ", "Barguna ", "Barisal ", "Bhola ", "Bogra ", "Brahmanbaria ", "Chandpur ", "Chittagong ", "Chuadanga ", "Comilla ", "Cox's Bazar ", "Dhaka ", "Dinajpur ", "Faridpur ", "Feni ", "Gaibandha ", "Gazipur ", "Gopalganj ", "Habiganj ", "Jaipurhat ", "Jamalpur ", "Jessore ", "Jhalakati ", "Jhenaidah ", "Khagrachari ", "Khulna ", "Kishoreganj ", "Kurigram ", "Kushtia ", "Lakshmipur ", "Lalmonirhat ", "Madaripur ", "Magura ", "Manikganj ", "Meherpur ", "Moulvibazar ", "Munshiganj ", "Mymensingh ", "Naogaon ", "Narail ", "Narayanganj ", "Narsingdi ", "Natore ", "Nawabganj ", "Netrakona ", "Nilphamari ", "Noakhali ", "Pabna ", "Panchagarh ", "Parbattya Chattagram", "Patuakhali ", "Pirojpur ", "Rajbari ", "Rajshahi ", "Rangpur ", "Satkhira ", "Shariatpur ", "Sherpur ", "Sirajganj ", "Sunamganj ", "Sylhet ", "Tangail ", "Thakurgaon " }));
        citybox.setBorder(null);
        searchpanel.add(citybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        day.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        searchpanel.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 45, -1));

        month.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        searchpanel.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 45, -1));

        year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018" }));
        searchpanel.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 67, -1));

        showdis.setEditable(false);
        showdis.setBackground(new java.awt.Color(240, 240, 240));
        showdis.setColumns(20);
        showdis.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        showdis.setRows(5);
        showdis.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jScrollPane1.setViewportView(showdis);

        searchpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 410, 280));

        jLabel35.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(52, 73, 94));
        jLabel35.setText("Search");
        searchpanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        getContentPane().add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 620, 360));

        showallpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alltotal.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        alltotal.setForeground(new java.awt.Color(52, 73, 94));
        alltotal.setText("Show All");
        showallpanel.add(alltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        showallpanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 36, 70, 10));

        showalldis.setEditable(false);
        showalldis.setBackground(new java.awt.Color(240, 240, 240));
        showalldis.setColumns(20);
        showalldis.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        showalldis.setRows(5);
        showalldis.setText("sdfd");
        showalldis.setMargin(new java.awt.Insets(2, 20, 2, 2));
        jScrollPane2.setViewportView(showalldis);

        showallpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 580, 280));

        jLabel36.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(52, 73, 94));
        jLabel36.setText("Show All");
        showallpanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        getContentPane().add(showallpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 620, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submiteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submiteditActionPerformed
       String name = ename.getText();
        String cell = ecell.getText();
        String user = euser.getText();
        String pass1 = epass.getText();
        String pass2 = epass1.getText();
        String bg=(String)ebg.getSelectedItem();
        String city =(String)ecity.getSelectedItem();
        int day=Integer.parseInt((String)eday.getSelectedItem());
        int month=Integer.parseInt((String)emonth.getSelectedItem());
        int year=Integer.parseInt((String)eyear.getSelectedItem());
        
        if(name.length()==0 || cell.length()==0 || user.length()==0 || pass1.length()==0 ){
            JOptionPane.showMessageDialog(null,"Fill up everything!");
            return;
        }
        
        if(!pass1.equals(pass2)){
             JOptionPane.showMessageDialog(null,"Password do not match!");
             return;
        }
        try {
            if(Home.duser.equals(user)){
                
            }
                
            else if(new Database().isUser(user)){
                JOptionPane.showMessageDialog(null,"Username Exist!\nTry another");
                return;
            }
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,"Connection Problem", "Error",JOptionPane.INFORMATION_MESSAGE);
        } 
        
        try {
           new Database().edit(name, cell, bg,city, day,month ,year , user, pass2);
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Connection Problem", "Error",JOptionPane.INFORMATION_MESSAGE);
       
       } 
       dname=name;
       dcell=cell;
       dbg=bg;
       dcity=city;
       duser=user;
       dpass=pass1;
       ddate=String.valueOf(day)+String.valueOf(month)+String.valueOf(year);
        JOptionPane.showMessageDialog(null,"Edit Successful!");
    }//GEN-LAST:event_submiteditActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
      setfalse();
      Profile.setVisible(true);
      name1.setText(dname);
      cell1.setText(dcell);
      blood1.setText(dbg);
      city1.setText(dcity);
      user1.setText(duser);
      pass1.setText(dpass);
      passhide.setText(dpass);
      date1.setText(ddate);
    }//GEN-LAST:event_profileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new Login().setVisible(true);
        close();
    }//GEN-LAST:event_logoutActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
              setfalse();
              Edit.setVisible(true);
              ename.setText(dname);
              ecell.setText(dcell);
              euser.setText(duser);
              epass.setText(dpass);
              epass1.setText(dpass);
              ecity.setSelectedIndex(Register.indexCity);
              ebg.setSelectedIndex(Register.indexBg);
              eday.setSelectedIndex(Register.ind);
              emonth.setSelectedIndex(Register.inm);
              eyear.setSelectedIndex(Register.iny);              
    }//GEN-LAST:event_editActionPerformed

    private void bserachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bserachActionPerformed
        long givenTime =  Integer.parseInt((String)day.getSelectedItem())+(30*Integer.parseInt((String)month.getSelectedItem()))+(30*12*Integer.parseInt((String)year.getSelectedItem()));
        String bg = (String)bgbox.getSelectedItem();
        String city= (String)citybox.getSelectedItem();
        System.out.println("input time: "+givenTime);
       try {
           showdis.setText(new Database().searchbg(givenTime,bg,city));
           
           } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Connection Problem", "Error",JOptionPane.INFORMATION_MESSAGE);
      }
       totaldis.setText("Total Availabe: "+String.valueOf(total));
    }//GEN-LAST:event_bserachActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        setfalse();
        searchpanel.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallActionPerformed
            setfalse();
            showallpanel.setVisible(true);
       try {
           showalldis.setText(new Database().showAll());
       } catch (Exception ex) {
          JOptionPane.showMessageDialog(null,"Connection Problem", "Error",JOptionPane.INFORMATION_MESSAGE);
       }
           alltotal.setText("Total Donor's: "+String.valueOf(total)); 
    }//GEN-LAST:event_showallActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String user1=user.getText();
       String pass1 = pass.getText();
       int p = JOptionPane.showConfirmDialog(null,"Do you want to delete your accout?","Delete",JOptionPane.YES_NO_OPTION);
       if(p==0){
           try {
                if(new Database().isLogin(user1,pass1)){
                    new Database().deleteAc(user1,pass1);
                    JOptionPane.showMessageDialog(null,"Delete Successful!");
                    new Login().setVisible(true);
                    close();
                }
                else
                    JOptionPane.showMessageDialog(null,"Wrong Password!");
               } catch (Exception ex) {
                     JOptionPane.showMessageDialog(null,"Connection Problem", "Error",JOptionPane.INFORMATION_MESSAGE);
                     }            
                }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        setfalse(); 
        deletepanel.setVisible(true);
        user.setText(duser);
    }//GEN-LAST:event_deleteActionPerformed

    private void enameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enameMouseClicked
       ename.setText("");
    }//GEN-LAST:event_enameMouseClicked

    private void ecellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ecellMouseClicked
        ecell.setText("");
    }//GEN-LAST:event_ecellMouseClicked

    private void euserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euserActionPerformed
        euser.setText("");
    }//GEN-LAST:event_euserActionPerformed

    private void epassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_epassKeyPressed
       
    }//GEN-LAST:event_epassKeyPressed

    private void epass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epass1MouseClicked
       epass1.setText("");
    }//GEN-LAST:event_epass1MouseClicked

    private void euserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_euserMouseClicked
        euser.setText("");
    }//GEN-LAST:event_euserMouseClicked

    private void epassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epassMouseClicked
        epass.setText("");
    }//GEN-LAST:event_epassMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            pass1.setVisible(true);
            passhide.setVisible(false);}
        else{
         pass1.setVisible(false);
            passhide.setVisible(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Edit;
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel alltotal;
    private javax.swing.JComboBox<String> bgbox;
    private javax.swing.JLabel blood1;
    private javax.swing.JButton bserach;
    private javax.swing.JLabel cell1;
    private javax.swing.JLabel city1;
    private javax.swing.JComboBox<String> citybox;
    private javax.swing.JLabel date1;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton delete;
    private javax.swing.JPanel deletepanel;
    private javax.swing.JComboBox<String> ebg;
    private javax.swing.JTextField ecell;
    private javax.swing.JComboBox<String> ecity;
    private javax.swing.JComboBox<String> eday;
    private javax.swing.JButton edit;
    private javax.swing.JComboBox<String> emonth;
    private javax.swing.JTextField ename;
    private javax.swing.JPasswordField epass;
    private javax.swing.JPasswordField epass1;
    private javax.swing.JTextField euser;
    private javax.swing.JComboBox<String> eyear;
    private javax.swing.JButton jButton10;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JLabel name1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pass1;
    private javax.swing.JPasswordField passhide;
    private javax.swing.JButton profile;
    private javax.swing.JLabel proname;
    private javax.swing.JButton search;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JButton showall;
    private javax.swing.JTextArea showalldis;
    private javax.swing.JPanel showallpanel;
    private javax.swing.JTextArea showdis;
    private javax.swing.JButton submitedit;
    private javax.swing.JLabel totaldis;
    private javax.swing.JTextField user;
    private javax.swing.JLabel user1;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
